### ISSUE TITLE
get-metadata: display a more user-friendly error when a wrong PR id is used

### ISSUE THREAD

**Issue by targos** [nodejs/node-core-utils#120]
Currently:
```
get-metadata 163754
× Getting commits from nodejs/node/pull/163754
×  GraphQL request Error
Error: GraphQL request Error
    at Request.request (C:\Users\targo\AppData\Roaming\nvm\v8.9.0\node_modules\node-core-utils\lib\request.js:50:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
{
  "variables": {
    "prid": 163754,
    "owner": "nodejs",
    "repo": "node"
  },
  "errors": [
    {
      "message": "Could not resolve to a PullRequest with the number of 163754.",
      "type": "NOT_FOUND",
      "path": [
        "repository",
        "pullRequest"
      ],
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ]
    }
  ]
}
```

**Comment by cPhost** [comment]
@targos , sure I will try to work on that.
