### ISSUE TITLE
rimraf is a dev dep

### ISSUE THREAD

**Issue by srl295** [nodejs/node-core-utils#145]
```$ git node land --abort
module.js:529
    throw err;
    ^

Error: Cannot find module 'rimraf'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-core-utils/lib/session.js:6:16)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

looks like `rimraf` is a dev and not a regular dependency

**Comment by srl295** [comment]
`cd /usr/local/lib/node_modules/node-core-utils ; npm i rimraf` worked around for now

**Comment by cPhost** [comment]
@joyeecheung looks like this slipped through the `git-node` PR and now used by `lib/session.js`.

**Comment by cPhost** [comment]
Made a PR to fix it, thanks @srl295 :)
