### ISSUE TITLE
error when core-validate-commit is installed globally

### ISSUE THREAD

**Issue by mcollina** [nodejs/node-core-utils#318]
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/matteo/.nvm/versions/node/v10.13.0/lib/node_modules/node-core-utils/node_modules/.bin/core-validate-commit ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by codebytere** [comment]
Closing as i no longer believe this is an issue but feel free to reopen if that's not the case.
