### ISSUE TITLE
Generate metadata for repo like https://github.com/nodejs/node-gyp/

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/node-core-utils#373]
Currently it fails with

```console
> git node metadata https://github.com/nodejs/node-gyp/pull/1944

✖  Failed to get collaborator info from nodejs/node-gyp/README.md
Error: Couldn't find ### TSC (Technical Steering Committee) in the README
    at parseCollaborators (/usr/local/lib/node_modules/node-core-utils/lib/collaborators.js:83:11)
    at getCollaborators (/usr/local/lib/node_modules/node-core-utils/lib/collaborators.js:61:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async PRData.getCollaborators (/usr/local/lib/node_modules/node-core-utils/lib/pr_data.js:77:26)
    at async Promise.all (index 0)
    at async PRData.getAll (/usr/local/lib/node_modules/node-core-utils/lib/pr_data.js:61:5)
    at async getMetadata (/usr/local/lib/node_modules/node-core-utils/components/metadata.js:19:3)
```

**Comment by gengjiawen** [comment]
Is it okay to make

https://github.com/nodejs/node-core-utils/blob/33666e1bda91b01c304c86e5c433edac0063ff06/lib/collaborators.js#L55

to this ?

```js
    const url = `https://raw.githubusercontent.com/nodejs/node/master/README.md`;
```

**Comment by legendecas** [comment]
> to this ?
> 
> ```js
>     const url = `https://raw.githubusercontent.com/nodejs/node/master/README.md`;
> ```

I think this is what's done in https://github.com/nodejs/node-review.
