### ISSUE TITLE
git node land crash if ncu-config wasn't set

### ISSUE THREAD

**Issue by targos** [nodejs/node-core-utils#423]
```
$ git node land --backport 33337
Error
    at exports.runSync (/home/mzasso/.nvm/versions/node/v14.3.0/lib/node_modules/node-core-utils/lib/run.js:60:11)
    at new Session (/home/mzasso/.nvm/versions/node/v14.3.0/lib/node_modules/node-core-utils/lib/session.js:28:26)
    at new LandingSession (/home/mzasso/.nvm/versions/node/v14.3.0/lib/node_modules/node-core-utils/lib/landing_session.js:17:5)
    at main (/home/mzasso/.nvm/versions/node/v14.3.0/lib/node_modules/node-core-utils/components/git/land.js:131:17)
    at land (/home/mzasso/.nvm/versions/node/v14.3.0/lib/node_modules/node-core-utils/components/git/land.js:114:21)
    at Object.handler (/home/mzasso/.nvm/versions/node/v14.3.0/lib/node_modules/node-core-utils/components/git/land.js:78:14)
    at Object.runCommand (/home/mzasso/.nvm/versions/node/v14.3.0/lib/node_modules/node-core-utils/node_modules/yargs/lib/command.js:240:40)
    at Object.parseArgs [as _parseArgs] (/home/mzasso/.nvm/versions/node/v14.3.0/lib/node_modules/node-core-utils/node_modules/yargs/yargs.js:1154:41)
    at Object.get [as argv] (/home/mzasso/.nvm/versions/node/v14.3.0/lib/node_modules/node-core-utils/node_modules/yargs/yargs.js:1088:21)
    at Object.<anonymous> (/home/mzasso/.nvm/versions/node/v14.3.0/lib/node_modules/node-core-utils/bin/git-node:20:3)
```

calling `ncu-config set upstream ` and `ncu-config set branch` fixed it.

**Comment by codebytere** [comment]
hmm, that should have tripped [this check](https://github.com/nodejs/node-core-utils/blob/189c167bd68206cae486c82fcf35db4e06ba13d1/components/git/land.js#L132-L134) 🤔

**Comment by targos** [comment]
I think there was no config file (removed previously with `git clean -fdx`).
