### ISSUE TITLE
is node-core-utils incompatible with node 14.4?

### ISSUE THREAD

**Issue by sam-github** [nodejs/node-core-utils#436]
I haven't troubleshot much, but I'm seeing

```
% ncu-team sync README.md         
✔  Received member information of nodejs/build                                                 
✔  Received member information of nodejs/build-infra                                                                                                                                           
✔  Received member information of nodejs/jenkins-admins
✔  Received member information of nodejs/jenkins-release-admins
✔  Received member information of nodejs/github-bot
Error: ENOENT: no such file or directory, mkdir 
    at Object.mkdirSync (fs.js:940:3)      
    at exports.writeFile (/home/sam/.nvm/versions/node/v12.16.3/lib/node_modules/node-core-utils/lib/file.js:18:8)
    at Function.TeamInfo.syncFile (/home/sam/.nvm/versions/node/v12.16.3/lib/node_modules/node-core-utils/lib/team_info.js:61:3)                                                               
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/home/sam/.nvm/versions/node/v12.16.3/lib/node_modules/node-core-utils/bin/ncu-team:64:7) {
  errno: -2,                         
  syscall: 'mkdir',                                                                            
  code: 'ENOENT'                                                                                                                                                                               
}
```

with node 14.4.0, so I backdated to 1.20.0, same, so I backdated node to 12.18.0, and it worked.

**Comment by joyeecheung** [comment]
It sounds like a regression of moving to the recursive option of `fs.mkdir`? @targos

**Comment by targos** [comment]
is it 100% reproducible?

**Comment by codebytere** [comment]
Pretty sure this was fixed by https://github.com/nodejs/node-core-utils/pull/434

**Comment by codebytere** [comment]
Closing as resolved
