### ISSUE TITLE
Occurs error when run git node 

### ISSUE THREAD

**Issue by luyahan** [nodejs/node-core-utils#661]
```
luyahan@plct-dev-7:~/source/node $ git node
/usr/local/lib/node_modules/node-core-utils/bin/git-node.js:3
import { readdirSync } from 'fs';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by luyahan** [comment]
Fix it by ppdate node  to v18
