### ISSUE TITLE
git node wpt <name> crashes if <name> isn't found

### ISSUE THREAD

**Issue by ThisIsMissEm** [nodejs/node-core-utils#664]
I just encountered this whilst trying to pull in the FileAPI tests for a backport, and I'd written:

```
$ git node wpt File
```

Instead of:

```
$ git node wpt FileAPI
```

Which resulted in the following crash:

```
$ git node wpt File
   ⚠  Please create File.json in test/wpt/status
------------------------- Checking updates for File... -------------------------
No records for File in local test/fixtures/wpt/versions.json
pulling files from scratch...
----------------- Writing assets to test/fixtures/wpt/File... ------------------
⠧ Querying asset list for File...TypeError: Cannot read properties of undefined (reading 'oid')
    at GitHubTree._getLastCommit (file:///usr/local/lib/node_modules/node-core-utils/lib/github/tree.js:38:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GitHubTree.getLastCommit (file:///usr/local/lib/node_modules/node-core-utils/lib/github/tree.js:48:23)
    at async GitHubTree.getFiles (file:///usr/local/lib/node_modules/node-core-utils/lib/github/tree.js:100:20)
    at async WPTUpdater.getAssetList (file:///usr/local/lib/node_modules/node-core-utils/lib/wpt/index.js:61:34)
    at async WPTUpdater.pullAllAssets (file:///usr/local/lib/node_modules/node-core-utils/lib/wpt/index.js:73:16)
    at async WPTUpdater.update (file:///usr/local/lib/node_modules/node-core-utils/lib/wpt/index.js:160:5)
    at async main (file:///usr/local/lib/node_modules/node-core-utils/components/git/wpt.js:80:5)```

It may need a check to see if the specified `<name>` is even a web platform test case, here I'd expect it to exit with -1 and a message saying "We couldn't find the File WPT tests, maybe you misspelled or have the wrong API identifier?"

**Comment by cyberbossone-coder** [comment]
- -
