### ISSUE TITLE
Unhelpful error message when using unknown remote

### ISSUE THREAD

**Issue by anonrig** [nodejs/node-core-utils#701]
I'm receiving a weird error running the following command:

```
git node land 48272
Error: git config,--get,remote.remote-upstream.url failed with stderr:
    at runSync (file:///Users/yagiz/.volta/tools/image/packages/node-core-utils/lib/node_modules/node-core-utils/lib/run.js:91:11)
    at new Session (file:///Users/yagiz/.volta/tools/image/packages/node-core-utils/lib/node_modules/node-core-utils/lib/session.js:30:26)
    at new LandingSession (file:///Users/yagiz/.volta/tools/image/packages/node-core-utils/lib/node_modules/node-core-utils/lib/landing_session.js:28:5)
    at main (file:///Users/yagiz/.volta/tools/image/packages/node-core-utils/lib/node_modules/node-core-utils/components/git/land.js:167:17)
```

**Comment by aduh95** [comment]
Can you paste the result of `cat .git/config` please?

**Comment by anonrig** [comment]
```

**Comment by aduh95** [comment]
You don't have a remote called `remote-upstream`, so ncu cannot read the URL assiciated with it. To fix the issue, you need to either create a remote `remote-upstream`, or change the `.ncu/config` file to use a different remote name (likely `upstream`).

**Comment by anonrig** [comment]
Ah, you're right. I've setup the NCU incorrectly. Thank you @aduh95

**Comment by aduh95** [comment]
We could still decide to change the default to be `upstream` rather than `remote-upstream` and/or improve the error message when the `git config` call fails to hint into what might be wrong.

**Comment by anonrig** [comment]
Definitely, that might be helpful, for cases like this.
