### ISSUE TITLE
git node wpt times out on large folders

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/node-core-utils#810]
`git node wpt fetch` or `git node wpt service-workers` consistently times out for me

```
   ⚠  Please create fetch.json in test/wpt/status
------------------------ Checking updates for fetch... -------------------------
No records for fetch in local test/fixtures/wpt/versions.json
pulling files from scratch...
----------------- Writing assets to test/fixtures/wpt/fetch... -----------------
✔  Read asset list, 796 files in total.
⠙ Downloaded test/fixtures/wpt/fetch/orb/resources/png-mislabeled-as-html.pngTypeError: fetch failed
    at fetch (/root/.volta/tools/image/packages/@node-core/utils/lib/node_modules/@node-core/utils/node_modules/undici/index.js:110:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async Request.buffer (file:///root/.volta/tools/image/packages/@node-core/utils/lib/node_modules/@node-core/utils/lib/request.js:40:17)
    at async WPTUpdater.pullTextFile (file:///root/.volta/tools/image/packages/@node-core/utils/lib/node_modules/@node-core/utils/lib/wpt/index.js:55:21)
    at async Promise.all (index 58)
    at async WPTUpdater.pullAllAssets (file:///root/.volta/tools/image/packages/@node-core/utils/lib/node_modules/@node-core/utils/lib/wpt/index.js:82:5)
    at async WPTUpdater.update (file:///root/.volta/tools/image/packages/@node-core/utils/lib/node_modules/@node-core/utils/lib/wpt/index.js:165:5) {
  cause: AggregateError
      at internalConnectMultiple (node:net:1114:18)
      at internalConnectMultiple (node:net:1177:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
      at listOnTimeout (node:internal/timers:575:11)
      at process.processTimers (node:internal/timers:514:7) {
    code: 'ETIMEDOUT',
    [errors]: [
      [Error], [Error],
      [Error], [Error],
      [Error], [Error],
      [Error], [Error]
    ]
  }
}
```

**Comment by KhafraDev** [comment]
Chunking the downloads fixes it for me, makes sense, opening 750-something connections simultaneously is probably going to cause issues.

```mjs
    for (let i = 0; i < assets.length; i += 10) {
      const chunk = assets.slice(i, i + 10)
      await Promise.all(chunk.map(
        (asset) => this.pullTextFile(fixtures, asset.name)
      ));
    }
```

https://github.com/nodejs/node-core-utils/blob/d7b00b533dd7ef455b4f4255e4e20fd1b05b6f59/lib/wpt/index.js#L82-L84
